#!/bin/bash

cat > val

time_zones=("-12" "-11" "-10" "-09" "-08" "-07" "-06" "-05" "-04" "-03" "-02" "-01" "00" "+01" "+02" "+03" "+04" "+05" "+06" "+07" "+08" "+09" "+10" "+11" "+12" "+13" "+14")
for i in ${time_zones[@]}

do
    param="\\${i}00"
    out="${i}00"
    out+=" $(grep "^Date:" val | grep -c "${param}$")"
    

    echo $out
    
done
